version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3409:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:php7.4-apache
    depends_on:
      - db
    user: root
    restart: always
    ports:
      - "9001:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      VIRTUAL_HOST: cyclops.localhost
      VIRTUAL_PORT: 80
    volumes:
      - ./:/var/www/html/wp-content/plugins/cyclops-demo
      - ./sample/conf/php.ini:/usr/local/etc/php/conf.d/uploads.ini
